# -*- coding: utf-8 -*-
"""Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KtMHysJNCNLh4XixljYK4LlGCivri4kG
"""

import numpy as np

def k_means(X, k=2, seed=None, tol=1e-4, max_iter=100):

    if seed is not None:
        np.random.seed(seed)

    n, d = X.shape

    # k points chosen randomly from the data and use those points as starting centers
    random_indices = np.random.choice(n, k, replace=False)
    centers = X[random_indices]

    inertia_history = []
    old_labels = np.zeros(n)

    for i in range(max_iter):
        # assignment
        # x_1, x_2, ..., x_n to every center (k).
        # (n, 1, d) - (k, d) -> (n, k, d)
        # norm across the dimension axis (axis 2)
        distances = np.linalg.norm(X[:, np.newaxis] - centers, axis=2)**2

        # assign each point to nearest centroid
        labels = np.argmin(distances, axis=1)

        # within cluster sum of squares objective
        current_inertia = np.sum(np.min(distances, axis=1))
        inertia_history.append(current_inertia)

        # update centers
        new_centers = np.array([X[labels == j].mean(axis=0) for j in range(k)])

        # convergence check
        if np.array_equal(labels, old_labels):
            break

        centers = new_centers
        old_labels = labels

    return labels, centers, inertia_history